#ifndef XBDM_GDB_BRIDGE_TEST_CONFIGURE_TEST_H_CMAKE_H_
#define XBDM_GDB_BRIDGE_TEST_CONFIGURE_TEST_H_CMAKE_H_

#define DYNDXT_LIB_DIR "${dyndxt_lib_dir}"

#endif  // XBDM_GDB_BRIDGE_TEST_CONFIGURE_TEST_H_CMAKE_H_
