// Adapted from xboxkrnl.exe.def
//    https://github.com/XboxDev/nxdk/blob/master/lib/xboxkrnl/xboxkrnl.exe.def
//
// Copyright (C) 2017 Stefan Schmidt
// This specific file is licensed under the CC0 1.0.
// Look here for details: https://creativecommons.org/publicdomain/zero/1.0/

#ifndef XBDM_GDB_BRIDGE_XBOXKRNL_EXPORTS_H
#define XBDM_GDB_BRIDGE_XBOXKRNL_EXPORTS_H

#define XBOX_AvGetSavedDataAddress 1
#define XBOX_AvSendTVEncoderOption 2
#define XBOX_AvSetDisplayMode 3
#define XBOX_AvSetSavedDataAddress 4
#define XBOX_DbgBreakPoint 5
#define XBOX_DbgBreakPointWithStatus 6
#define XBOX_DbgLoadImageSymbols 7
#define XBOX_DbgPrint 8
#define XBOX_HalReadSMCTrayState 9
#define XBOX_DbgPrompt 10
#define XBOX_DbgUnLoadImageSymbols 11
#define XBOX_ExAcquireReadWriteLockExclusive 12
#define XBOX_ExAcquireReadWriteLockShared 13
#define XBOX_ExAllocatePool 14
#define XBOX_ExAllocatePoolWithTag 15
#define XBOX_ExEventObjectType 16
#define XBOX_ExFreePool 17
#define XBOX_ExInitializeReadWriteLock 18
#define XBOX_ExInterlockedAddLargeInteger 19
#define XBOX_ExInterlockedAddLargeStatistic 20
#define XBOX_ExInterlockedCompareExchange64 21
#define XBOX_ExMutantObjectType 22
#define XBOX_ExQueryPoolBlockSize 23
#define XBOX_ExQueryNonVolatileSetting 24
#define XBOX_ExReadWriteRefurbInfo 25
#define XBOX_ExRaiseException 26
#define XBOX_ExRaiseStatus 27
#define XBOX_ExReleaseReadWriteLock 28
#define XBOX_ExSaveNonVolatileSetting 29
#define XBOX_ExSemaphoreObjectType 30
#define XBOX_ExTimerObjectType 31
#define XBOX_ExfInterlockedInsertHeadList 32
#define XBOX_ExfInterlockedInsertTailList 33
#define XBOX_ExfInterlockedRemoveHeadList 34
#define XBOX_FscGetCacheSize 35
#define XBOX_FscInvalidateIdleBlocks 36
#define XBOX_FscSetCacheSize 37
#define XBOX_HalClearSoftwareInterrupt 38
#define XBOX_HalDisableSystemInterrupt 39
#define XBOX_HalDiskCachePartitionCount 40
#define XBOX_HalDiskModelNumber 41
#define XBOX_HalDiskSerialNumber 42
#define XBOX_HalEnableSystemInterrupt 43
#define XBOX_HalGetInterruptVector 44
#define XBOX_HalReadSMBusValue 45
#define XBOX_HalReadWritePCISpace 46
#define XBOX_HalRegisterShutdownNotification 47
#define XBOX_HalRequestSoftwareInterrupt 48
#define XBOX_HalReturnToFirmware 49
#define XBOX_HalWriteSMBusValue 50
#define XBOX_InterlockedCompareExchange 51
#define XBOX_InterlockedDecrement 52
#define XBOX_InterlockedIncrement 53
#define XBOX_InterlockedExchange 54
#define XBOX_InterlockedExchangeAdd 55
#define XBOX_InterlockedFlushSList 56
#define XBOX_InterlockedPopEntrySList 57
#define XBOX_InterlockedPushEntrySList 58
#define XBOX_IoAllocateIrp 59
#define XBOX_IoBuildAsynchronousFsdRequest 60
#define XBOX_IoBuildDeviceIoControlRequest 61
#define XBOX_IoBuildSynchronousFsdRequest 62
#define XBOX_IoCheckShareAccess 63
#define XBOX_IoCompletionObjectType 64
#define XBOX_IoCreateDevice 65
#define XBOX_IoCreateFile 66
#define XBOX_IoCreateSymbolicLink 67
#define XBOX_IoDeleteDevice 68
#define XBOX_IoDeleteSymbolicLink 69
#define XBOX_IoDeviceObjectType 70
#define XBOX_IoFileObjectType 71
#define XBOX_IoFreeIrp 72
#define XBOX_IoInitializeIrp 73
#define XBOX_IoInvalidDeviceRequest 74
#define XBOX_IoQueryFileInformation 75
#define XBOX_IoQueryVolumeInformation 76
#define XBOX_IoQueueThreadIrp 77
#define XBOX_IoRemoveShareAccess 78
#define XBOX_IoSetIoCompletion 79
#define XBOX_IoSetShareAccess 80
#define XBOX_IoStartNextPacket 81
#define XBOX_IoStartNextPacketByKey 82
#define XBOX_IoStartPacket 83
#define XBOX_IoSynchronousDeviceIoControlRequest 84
#define XBOX_IoSynchronousFsdRequest 85
#define XBOX_IofCallDriver 86
#define XBOX_IofCompleteRequest 87
#define XBOX_KdDebuggerEnabled 88
#define XBOX_KdDebuggerNotPresent 89
#define XBOX_IoDismountVolume 90
#define XBOX_IoDismountVolumeByName 91
#define XBOX_KeAlertResumeThread 92
#define XBOX_KeAlertThread 93
#define XBOX_KeBoostPriorityThread 94
#define XBOX_KeBugCheck 95
#define XBOX_KeBugCheckEx 96
#define XBOX_KeCancelTimer 97
#define XBOX_KeConnectInterrupt 98
#define XBOX_KeDelayExecutionThread 99
#define XBOX_KeDisconnectInterrupt 100
#define XBOX_KeEnterCriticalRegion 101
#define XBOX_MmGlobalData 102
#define XBOX_KeGetCurrentIrql 103
#define XBOX_KeGetCurrentThread 104
#define XBOX_KeInitializeApc 105
#define XBOX_KeInitializeDeviceQueue 106
#define XBOX_KeInitializeDpc 107
#define XBOX_KeInitializeEvent 108
#define XBOX_KeInitializeInterrupt 109
#define XBOX_KeInitializeMutant 110
#define XBOX_KeInitializeQueue 111
#define XBOX_KeInitializeSemaphore 112
#define XBOX_KeInitializeTimerEx 113
#define XBOX_KeInsertByKeyDeviceQueue 114
#define XBOX_KeInsertDeviceQueue 115
#define XBOX_KeInsertHeadQueue 116
#define XBOX_KeInsertQueue 117
#define XBOX_KeInsertQueueApc 118
#define XBOX_KeInsertQueueDpc 119
#define XBOX_KeInterruptTime 120
#define XBOX_KeIsExecutingDpc 121
#define XBOX_KeLeaveCriticalRegion 122
#define XBOX_KePulseEvent 123
#define XBOX_KeQueryBasePriorityThread 124
#define XBOX_KeQueryInterruptTime 125
#define XBOX_KeQueryPerformanceCounter 126
#define XBOX_KeQueryPerformanceFrequency 127
#define XBOX_KeQuerySystemTime 128
#define XBOX_KeRaiseIrqlToDpcLevel 129
#define XBOX_KeRaiseIrqlToSynchLevel 130
#define XBOX_KeReleaseMutant 131
#define XBOX_KeReleaseSemaphore 132
#define XBOX_KeRemoveByKeyDeviceQueue 133
#define XBOX_KeRemoveDeviceQueue 134
#define XBOX_KeRemoveEntryDeviceQueue 135
#define XBOX_KeRemoveQueue 136
#define XBOX_KeRemoveQueueDpc 137
#define XBOX_KeResetEvent 138
#define XBOX_KeRestoreFloatingPointState 139
#define XBOX_KeResumeThread 140
#define XBOX_KeRundownQueue 141
#define XBOX_KeSaveFloatingPointState 142
#define XBOX_KeSetBasePriorityThread 143
#define XBOX_KeSetDisableBoostThread 144
#define XBOX_KeSetEvent 145
#define XBOX_KeSetEventBoostPriority 146
#define XBOX_KeSetPriorityProcess 147
#define XBOX_KeSetPriorityThread 148
#define XBOX_KeSetTimer 149
#define XBOX_KeSetTimerEx 150
#define XBOX_KeStallExecutionProcessor 151
#define XBOX_KeSuspendThread 152
#define XBOX_KeSynchronizeExecution 153
#define XBOX_KeSystemTime 154
#define XBOX_KeTestAlertThread 155
#define XBOX_KeTickCount 156
#define XBOX_KeTimeIncrement 157
#define XBOX_KeWaitForMultipleObjects 158
#define XBOX_KeWaitForSingleObject 159
#define XBOX_KfRaiseIrql 160
#define XBOX_KfLowerIrql 161
#define XBOX_KiBugCheckData 162
#define XBOX_KiUnlockDispatcherDatabase 163
#define XBOX_LaunchDataPage 164
#define XBOX_MmAllocateContiguousMemory 165
#define XBOX_MmAllocateContiguousMemoryEx 166
#define XBOX_MmAllocateSystemMemory 167
#define XBOX_MmClaimGpuInstanceMemory 168
#define XBOX_MmCreateKernelStack 169
#define XBOX_MmDeleteKernelStack 170
#define XBOX_MmFreeContiguousMemory 171
#define XBOX_MmFreeSystemMemory 172
#define XBOX_MmGetPhysicalAddress 173
#define XBOX_MmIsAddressValid 174
#define XBOX_MmLockUnlockBufferPages 175
#define XBOX_MmLockUnlockPhysicalPage 176
#define XBOX_MmMapIoSpace 177
#define XBOX_MmPersistContiguousMemory 178
#define XBOX_MmQueryAddressProtect 179
#define XBOX_MmQueryAllocationSize 180
#define XBOX_MmQueryStatistics 181
#define XBOX_MmSetAddressProtect 182
#define XBOX_MmUnmapIoSpace 183
#define XBOX_NtAllocateVirtualMemory 184
#define XBOX_NtCancelTimer 185
#define XBOX_NtClearEvent 186
#define XBOX_NtClose 187
#define XBOX_NtCreateDirectoryObject 188
#define XBOX_NtCreateEvent 189
#define XBOX_NtCreateFile 190
#define XBOX_NtCreateIoCompletion 191
#define XBOX_NtCreateMutant 192
#define XBOX_NtCreateSemaphore 193
#define XBOX_NtCreateTimer 194
#define XBOX_NtDeleteFile 195
#define XBOX_NtDeviceIoControlFile 196
#define XBOX_NtDuplicateObject 197
#define XBOX_NtFlushBuffersFile 198
#define XBOX_NtFreeVirtualMemory 199
#define XBOX_NtFsControlFile 200
#define XBOX_NtOpenDirectoryObject 201
#define XBOX_NtOpenFile 202
#define XBOX_NtOpenSymbolicLinkObject 203
#define XBOX_NtProtectVirtualMemory 204
#define XBOX_NtPulseEvent 205
#define XBOX_NtQueueApcThread 206
#define XBOX_NtQueryDirectoryFile 207
#define XBOX_NtQueryDirectoryObject 208
#define XBOX_NtQueryEvent 209
#define XBOX_NtQueryFullAttributesFile 210
#define XBOX_NtQueryInformationFile 211
#define XBOX_NtQueryIoCompletion 212
#define XBOX_NtQueryMutant 213
#define XBOX_NtQuerySemaphore 214
#define XBOX_NtQuerySymbolicLinkObject 215
#define XBOX_NtQueryTimer 216
#define XBOX_NtQueryVirtualMemory 217
#define XBOX_NtQueryVolumeInformationFile 218
#define XBOX_NtReadFile 219
#define XBOX_NtReadFileScatter 220
#define XBOX_NtReleaseMutant 221
#define XBOX_NtReleaseSemaphore 222
#define XBOX_NtRemoveIoCompletion 223
#define XBOX_NtResumeThread 224
#define XBOX_NtSetEvent 225
#define XBOX_NtSetInformationFile 226
#define XBOX_NtSetIoCompletion 227
#define XBOX_NtSetSystemTime 228
#define XBOX_NtSetTimerEx 229
#define XBOX_NtSignalAndWaitForSingleObjectEx 230
#define XBOX_NtSuspendThread 231
#define XBOX_NtUserIoApcDispatcher 232
#define XBOX_NtWaitForSingleObject 233
#define XBOX_NtWaitForSingleObjectEx 234
#define XBOX_NtWaitForMultipleObjectsEx 235
#define XBOX_NtWriteFile 236
#define XBOX_NtWriteFileGather 237
#define XBOX_NtYieldExecution 238
#define XBOX_ObCreateObject 239
#define XBOX_ObDirectoryObjectType 240
#define XBOX_ObInsertObject 241
#define XBOX_ObMakeTemporaryObject 242
#define XBOX_ObOpenObjectByName 243
#define XBOX_ObOpenObjectByPointer 244
#define XBOX_ObpObjectHandleTable 245
#define XBOX_ObReferenceObjectByHandle 246
#define XBOX_ObReferenceObjectByName 247
#define XBOX_ObReferenceObjectByPointer 248
#define XBOX_ObSymbolicLinkObjectType 249
#define XBOX_ObfDereferenceObject 250
#define XBOX_ObfReferenceObject 251
#define XBOX_PhyGetLinkState 252
#define XBOX_PhyInitialize 253
#define XBOX_PsCreateSystemThread 254
#define XBOX_PsCreateSystemThreadEx 255
#define XBOX_PsQueryStatistics 256
#define XBOX_PsSetCreateThreadNotifyRoutine 257
#define XBOX_PsTerminateSystemThread 258
#define XBOX_PsThreadObjectType 259
#define XBOX_RtlAnsiStringToUnicodeString 260
#define XBOX_RtlAppendStringToString 261
#define XBOX_RtlAppendUnicodeStringToString 262
#define XBOX_RtlAppendUnicodeToString 263
#define XBOX_RtlAssert 264
#define XBOX_RtlCaptureContext 265
#define XBOX_RtlCaptureStackBackTrace 266
#define XBOX_RtlCharToInteger 267
#define XBOX_RtlCompareMemory 268
#define XBOX_RtlCompareMemoryUlong 269
#define XBOX_RtlCompareString 270
#define XBOX_RtlCompareUnicodeString 271
#define XBOX_RtlCopyString 272
#define XBOX_RtlCopyUnicodeString 273
#define XBOX_RtlCreateUnicodeString 274
#define XBOX_RtlDowncaseUnicodeChar 275
#define XBOX_RtlDowncaseUnicodeString 276
#define XBOX_RtlEnterCriticalSection 277
#define XBOX_RtlEnterCriticalSectionAndRegion 278
#define XBOX_RtlEqualString 279
#define XBOX_RtlEqualUnicodeString 280
#define XBOX_RtlExtendedIntegerMultiply 281
#define XBOX_RtlExtendedLargeIntegerDivide 282
#define XBOX_RtlExtendedMagicDivide 283
#define XBOX_RtlFillMemory 284
#define XBOX_RtlFillMemoryUlong 285
#define XBOX_RtlFreeAnsiString 286
#define XBOX_RtlFreeUnicodeString 287
#define XBOX_RtlGetCallersAddress 288
#define XBOX_RtlInitAnsiString 289
#define XBOX_RtlInitUnicodeString 290
#define XBOX_RtlInitializeCriticalSection 291
#define XBOX_RtlIntegerToChar 292
#define XBOX_RtlIntegerToUnicodeString 293
#define XBOX_RtlLeaveCriticalSection 294
#define XBOX_RtlLeaveCriticalSectionAndRegion 295
#define XBOX_RtlLowerChar 296
#define XBOX_RtlMapGenericMask 297
#define XBOX_RtlMoveMemory 298
#define XBOX_RtlMultiByteToUnicodeN 299
#define XBOX_RtlMultiByteToUnicodeSize 300
#define XBOX_RtlNtStatusToDosError 301
#define XBOX_RtlRaiseException 302
#define XBOX_RtlRaiseStatus 303
#define XBOX_RtlTimeFieldsToTime 304
#define XBOX_RtlTimeToTimeFields 305
#define XBOX_RtlTryEnterCriticalSection 306
#define XBOX_RtlUlongByteSwap 307
#define XBOX_RtlUnicodeStringToAnsiString 308
#define XBOX_RtlUnicodeStringToInteger 309
#define XBOX_RtlUnicodeToMultiByteN 310
#define XBOX_RtlUnicodeToMultiByteSize 311
#define XBOX_RtlUnwind 312
#define XBOX_RtlUpcaseUnicodeChar 313
#define XBOX_RtlUpcaseUnicodeString 314
#define XBOX_RtlUpcaseUnicodeToMultiByteN 315
#define XBOX_RtlUpperChar 316
#define XBOX_RtlUpperString 317
#define XBOX_RtlUshortByteSwap 318
#define XBOX_RtlWalkFrameChain 319
#define XBOX_RtlZeroMemory 320
#define XBOX_XboxEEPROMKey 321
#define XBOX_XboxHardwareInfo 322
#define XBOX_XboxHDKey 323
#define XBOX_XboxKrnlVersion 324
#define XBOX_XboxSignatureKey 325
#define XBOX_XeImageFileName 326
#define XBOX_XeLoadSection 327
#define XBOX_XeUnloadSection 328
#define XBOX_READ_PORT_BUFFER_UCHAR 329
#define XBOX_READ_PORT_BUFFER_USHORT 330
#define XBOX_READ_PORT_BUFFER_ULONG 331
#define XBOX_WRITE_PORT_BUFFER_UCHAR 332
#define XBOX_WRITE_PORT_BUFFER_USHORT 333
#define XBOX_WRITE_PORT_BUFFER_ULONG 334
#define XBOX_XcSHAInit 335
#define XBOX_XcSHAUpdate 336
#define XBOX_XcSHAFinal 337
#define XBOX_XcRC4Key 338
#define XBOX_XcRC4Crypt 339
#define XBOX_XcHMAC 340
#define XBOX_XcPKEncPublic 341
#define XBOX_XcPKDecPrivate 342
#define XBOX_XcPKGetKeyLen 343
#define XBOX_XcVerifyPKCS1Signature 344
#define XBOX_XcModExp 345
#define XBOX_XcDESKeyParity 346
#define XBOX_XcKeyTable 347
#define XBOX_XcBlockCrypt 348
#define XBOX_XcBlockCryptCBC 349
#define XBOX_XcCryptService 350
#define XBOX_XcUpdateCrypto 351
#define XBOX_RtlRip 352
#define XBOX_XboxLANKey 353
#define XBOX_XboxAlternateSignatureKeys 354
#define XBOX_XePublicKeyData 355
#define XBOX_HalBootSMCVideoMode 356
#define XBOX_IdexChannelObject 357
#define XBOX_HalIsResetOrShutdownPending 358
#define XBOX_IoMarkIrpMustComplete 359
#define XBOX_HalInitiateShutdown 360
#define XBOX_RtlSnprintf 361
#define XBOX_RtlSprintf 362
#define XBOX_RtlVsnprintf 363
#define XBOX_RtlVsprintf 364
#define XBOX_HalEnableSecureTrayEject 365
#define XBOX_HalWriteSMCScratchRegister 366
#define XBOX_MmDbgAllocateMemory 374
#define XBOX_MmDbgFreeMemory 375
#define XBOX_MmDbgQueryAvailablePages 376
#define XBOX_MmDbgReleaseAddress 377
#define XBOX_MmDbgWriteCheck 378

#endif  // XBDM_GDB_BRIDGE_XBOXKRNL_EXPORTS_H
