#ifndef XBDM_GDB_BRIDGE_EXECUTION_STATE_H
#define XBDM_GDB_BRIDGE_EXECUTION_STATE_H

enum ExecutionState {
  S_INVALID = -1,
  S_STOPPED,
  S_STARTED,
  S_REBOOTING,
  S_PENDING,
};

#endif  // XBDM_GDB_BRIDGE_EXECUTION_STATE_H
