#ifndef XBDM_GDB_BRIDGE_CONFIGURE_H_IN_H
#define XBDM_GDB_BRIDGE_CONFIGURE_H_IN_H

#cmakedefine HAVE_HTONLL
#cmakedefine HAVE_BE64TOH

#cmakedefine ENABLE_HIGH_VERBOSITY_LOGGING

#endif  // XBDM_GDB_BRIDGE_CONFIGURE_H_IN_H
